#!/usr/bin/env bash
set -euo pipefail

# stagingされているpythonがなければ、フックを終了
if [[ -z "$( git diff --cached --name-only '*.py' )" ]]; then
  exit 0
fi

# stagingされているpythonファイルがあればlintする
git diff --cached --name-only -z '*.py' | xargs -0 poetry run black --diff --check
